console.log("this is my file now");
console.log("🦝🦝🦝🦝🦝🦝🦝🦝");
console.log("🐶🐶🐶🐶🐶🐶");
console.log("🐈‍⬛🐈‍⬛🐈‍⬛🐈‍⬛🐈‍⬛🐈‍⬛");
console.log("🐈‍⬛🐈‍⬛🐈‍⬛🐈‍⬛🐈‍⬛🐈‍⬛");
console.log("🐍🐍🐍🐍🐍🐍🐍");
console.log("🦝🦝🦝🦝🦝🦝🦝🦝");
console.log("🦁🦁🦁🦁🦁🦁🦁🦁");
console.log("🦁🦁🦁🦁🦁🦁🦁🦁");
console.log("🦁🦁🦁🦁🦁🦁🦁🦁");
console.log("🦄🦄🦄🦄🦄🦄");
console.log("🦄🦄🦄🦄🦄🦄");
console.log("🦄🦄🦄🦄🦄🦄");
